data_dirs:
  data_aggregated_dir: ../03-data-aggregated
  data_compiled_dir: ../07-data-compiled
  data_facts_dir: ../00-data-facts
  data_html_dir: ../01-data-html
  data_indexed_dir: ../05-data-indexed
  data_normalized_dir: ../04-data-normalized
  data_parsed_dir: ../02-data-parsed
  data_reindexed_dir: ../06-data-normalized-reindexed
  experiments_dir: ../08-experiments
experiment:
  description: null
  experiment_name: null
  feature_selection:
    mode: percentile
    params:
    - 5
    - 10
    # - 15
    # - 20
    # - 35
    # - 50
    # - 75
    scoring_funcs: classification
  model_selection:
    cv: 3
    model_params: classification
    models: classification
    scoring_funcs: classification
src_data:
  label_name: W/L
  src_dir: ../07-data-compiled/dataset-ss0110-mnmx-7fg
tgt_data:
  tgt_dir: ../08-experiments/dataset-ss0110-mnmx-7fg
